### ISSUE TITLE
How to deploy API Management content from one tenant to other using Git and CI/CD pipeline

### ISSUE THREAD

**Issue by Srinu3366** [SAP/cloud-api-management-samples#6]
Is it possible to store the API Management content in a Git repository and then deploying it using a CI/CD tool?

**Comment by i850899** [comment]
At least one SAP customer developed a Git pipeline with Jenkins for transport of APIM content between landscapes. Was quite nifty in fact.

**Comment by Srinu3366** [comment]
Any pointers on how they accomplished it? 

The only option I see is downloading the content manually and then adding it to a repository. We want to make it more developer friendly than asking to manually do it.

**Comment by aadinigam** [comment]
We have APIs available for [SAP Cloud Platform API Management ](https://api.sap.com/package/APIMgmt?section=Artifacts) that can be used to create automation

Specifically in this case i believe the [Transport APIs ](https://api.sap.com/api/APIPortal_Transport/resource) will help

**Comment by Srinu3366** [comment]
We are able to make some progress getting the API Proxy and add it to git repo from a pipeline. Now we are facing an issue with POST to deploy the API to new sub-account. It is giving 403 error. I am able to import the API from the UI but getting error while trying with POST method in Transport API. 

Anyone faced same issue?

**Comment by Srinu3366** [comment]
How to get the value of virtualhost for an API Management tenant?

**Comment by Srinu3366** [comment]
It worked now. We updated the build script to get csrf token and send it with POST along with the session cookie.

We have a high level CI/CD pipeline working now. 

Thanks for your inputs. Closing the issue now.

**Comment by subitb** [comment]
Hi Srinu3366

@Srinu3366 Could you please elaborate this steps to bit further.Did you use Transport APIs for creating Jenkins pipeline.So Could please elaborate each step in this process bit more elaborately as I am looking for the same situation.

Kind Regards
Subit Benny

**Comment by Srinu3366** [comment]
> Hi Srinu3366
> 
> @Srinu3366 Could you please elaborate this steps to bit further.Did you use Transport APIs for creating Jenkins pipeline.So Could please elaborate each step in this process bit more elaborately as I am looking for the same situation.
> 
> Kind Regards
> Subit Benny

Are you still looking for the solution? 

We created a node.js script to download the API Proxy details and then developer manually commits and pushes to a git repository. Then we have a pipeline to validate the API Proxy using postman tests and then deploy using another node.js script.

**Comment by Tis89** [comment]
Hi Srinu3366,
@Srinu3366 did you solve you 403 Error with setting the csrf token or did you also set the session cookie. By setting the csrf token we get the same error in jenkins, when we try the same post with postman it works.

Thank you and Kind regards

Tim
